name: 'Installer 1C:Enterprise 8 and 1C:EDT'
description: 'Allows you to install 1C:Enterprise 8 or 1C:EDT of the required version'
author: '1CDevFlow'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  type:
    required: true
    description: 'type of installer(edt or onec)'
    default: ''
  edt_version:
    required: false
    description: 'edt version'
    default: '2023.1.2'
  onec_version:
    required: false
    description: 'onec version'
    default: '8.3.20.1549'
  cache:
    required: false
    description: 'use cache'
    default: 'true'
  cache_distr:
    required: false
    description: 'use cache distributives'
    default: 'false'
runs:
  using: node20
  main: dist/index.js
