env:
  node: true
  es6: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/.*'
  - '**/dist/.*'
  - '**/coverage/.*'
  - '**/__tests__/**'
  - '*.json'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2023
  sourceType: module

plugins:
  - jest
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended

rules:
  'no-console': 'off'
  'no-unused-vars': 'off'
  '@typescript-eslint/no-explicit-any': 'warn'
  '@typescript-eslint/no-unused-vars': 'error'
