env:
  node: true
  es6: true

ignorePatterns:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/coverage/**'
  - '**/__tests__/**'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2023
  sourceType: module

plugins:
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

rules:
  'no-console': 'off'
  'no-unused-vars': 'off'
  '@typescript-eslint/no-explicit-any': 'warn'
  '@typescript-eslint/no-unused-vars': 'error'
